pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.3-openjdk-11-slim' }
      }
      steps {
        // Checkout your Java project from Git
        git(url: 'https://github.com/Arjun0889/Jenkins-Zero-To-Hero/blob/main/HelloWorld.java', branch: 'main')
        
        // Build and test your Java application
        sh 'mvn clean install'  // Modify this command as per your project's build process
        
        // Run the Java application
        sh 'java -cp target/your-java-application.jar HelloWorld'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        // Checkout your Node.js project from Git
        git(url: 'https://github.com/Arjun0889/Jenkins-Zero-To-Hero/blob/main/app.js', branch: 'main')
        
        // Install Node.js dependencies
        sh 'npm install'
        
        // Build and test your Node.js application
        sh 'node --version'
        
        // Run the Node.js application
        sh 'node app.js'
      }
    }
  }
}
